### PR TITLE
Adds a message when an empty string is provided

### LINKED ISSUE #497: Print something for `str_view(character())`
Should be adequate to fix just `print.stringr_view()` by adding a special case for `n = 0`.  I'm not sure what it should print though! Probably just something that it says "no strings", but more nicely 😄 

Will need a snapshot test.

### PR DESCRIPTION
**Pull request by LouisMPenrod**
Returns a message instead of returning nothing which was the previous behavior. Existing snapshot updated.

Fixes #497

### CODE REVIEW

**Comment by hadley** [comment]
@DavisVaughan do you remember what we've done when we've printed length-0 objects in other packages?

**Comment by DavisVaughan** [comment]
You _could_ use the vctrs approach and always unconditionally print a header

```r
> vctrs::obj_print(1)
<double[1]>
[1] 1
> vctrs::obj_print(double())
<double[0]>
```

Like `<stringr_view[0]>` or something. So even in the empty case you get something.

---

But since this is mostly for interactive usage I don't mind something like `No strings provided` or something equally friendly. I don't really mind the current behavior much though, it is like `glue::glue()`.

Do we also want to consider the `str_view(character(), html = TRUE)` case?

**Comment by hadley** [comment]
I consider `html = TRUE` basically superseded so no need to worry about it, I think.

**Comment by hadley** [comment]
Thanks for working on this and I hope you had fun at TDD 😁

**Pull request merged**
