### PR TITLE
Added a trim function that I expect to have

### PR DESCRIPTION
**Pull request by stephlocke**
I'm used to trim functions removing spaces from the middle of strings too. This str_trim_all function therefore does string trim left, center, and right.

PR has new function, man page, and tests.

### CODE REVIEW

**Comment by smbache** [comment]
How about naming it `squish` as it is called in e.g. ruby :)

**Comment by stephlocke** [comment]
Sure so `str_squish` ?

**Comment by smbache** [comment]
Sure... just a suggestion ;) not my pkg

**Comment by stephlocke** [comment]
Changed to str_squish as the name sense

**Comment by hadley** [comment]
Can you please move to new home (in `trim.R)` and document with `str_trim()`? Thanks!

**Comment by stephlocke** [comment]
Sure thing

**Comment by hadley** [comment]
By "document with", I meant use `@rdname str_trim` so there's only one .Rd file. Sorry for not being more clear!

Can you please add a bullet to NEWS? It should briefly describe the change (starting with name of the function), and crediting yourself with `(@yourname, #issuenumber)`.

**Comment by stephlocke** [comment]
Closing this PR - the rebase onto latest master was too much for a Sunday night :)

**Pull request closed without merging**
