### PR TITLE
Added str_to_sentence function.

### LINKED ISSUE #202: str_to_sentence
Hi, could we please have a function that converts a string to sentence case. Some code below with my attempt at this..

str_to_sentence <- function(x) {
  paste0(str_to_upper(str_sub(x, 1, 1)), str_to_lower(str_sub(x, 2)))
  }

### PR DESCRIPTION
**Pull request by jonthegeek**
Closes #202 .

### CODE REVIEW

**Comment by hadley** [comment]
It looks like there's some whitespace problem in the NAMESPACE. Would you mind checking in roxygen2 to see if there's already an issue? (I assume you're using windows, but roxygen2 should handle this)

**Comment by hadley** [comment]
Can you please add a bullet to NEWS? It should briefly [describe the change](http://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

**Comment by hadley** [comment]
(I'll can fix the whitespace issue, but I want to make sure it's tracked somewhere)

**Comment by jonthegeek** [comment]
> It looks like there's some whitespace problem in the NAMESPACE. Would you mind checking in roxygen2 to see if there's already an issue? (I assume you're using windows, but roxygen2 should handle this)

I'm trying to understand what the issue is to help me search for it in roxygen2 (and then, I think, open an issue, because it isn't clear to me what happened but I don't see a related issue).

**Pull request merged**
