### PR TITLE
Add str_left(), str_right() and str_mid() functions.

### PR DESCRIPTION
**Pull request by chrimaho**
Requesting to add the `str_left()`, `str_right()` and `str_mid()` functions to the `sub.r` file. These new functions are simply wrappers around the `base::substr()` function. The reason for this request is to make the syntax and function naming similar to the Excel functions that to the same process.  The whole purpose of these functions is to make the life of an R Coder easier; especially if they are newly upgrading from the Excel environment. Essentially, these functions are direct equivalents to the very popular Excel functions: `LEFT()`, `RIGHT()` and `MID()`.

### CODE REVIEW

**Comment by cderv** [comment]
I find this a nice idea to have some excel-like function like that. It could help transitions. 👍 
Just a tip I wanted to share: `stringr` is already heavily based on `stringi` and you have a `stringi::stri_sub()` that exists and can be useful alternative to base function to get more closely aligned with other functions.

**Comment by chrimaho** [comment]
Hey mate, Thanks!
I definitely agree that it would be better to align to `stringi` functions than to `base` functions. And when I was reviewing the `stringr::str_sub()` function, I saw that it also referenced `@seealso The underlying implementation in [stringi::stri_sub()]`.
I included those `base` examples in my code as a point of reference so that people can see that there were already other ways of achieving this functionality. So, I'm not really re-inventing the wheel here, just re-phrasing it to make the Excel-to-R transition easier for our future R community.
Would you like me to change the examples to reference the `stringi` functions, then re-submit the Pull Request?

**Comment by cderv** [comment]
No. Don't change anything. I just wanted to give cheers to this idea and share some thoughts. 
I used some wrappers once using `stringr` function instead of based R to get it vectorized.
``` r
str_left <- function(string, num_chars) {
  stringr::str_sub(string, start = 1, end = num_chars)
}
str_left("abcdfe", c(1, 2))
#> [1] "a"  "ab"
```
That's why I wanted to give a big +1 to the idea. 😄

**Comment by hadley** [comment]
I appreciate your enthusiasm but the code style is very far away from the existing stringr style. I'm also not terribly convinced by the utility of these functions given the flexibility of `str_sub()`, and I'm worried that stringr is getting too many functions that do very similar things.

**Pull request closed without merging**
